INSERT INTO ARTIST (ARTIST_NAME, ARTIST_COUNTRY) VALUES
    ('Nguyen Van A', 'VietNam'),
    ('Nguyen Thi B', 'VietNam'),
    ('Tran C', 'VietNam');
    
INSERT INTO SONG (SONG_TITLE, SONG_DURATION, SONG_GENRE, ARTIST_ID) VALUES
    ('Muon ruou to tinh', '3min', 'Male', (SELECT ARTIST_ID FROM ARTIST WHERE ARTIST_NAME = 'Nguyen Van A')),
    ('Abc', '5min', 'Male', (SELECT ARTIST_ID FROM ARTIST WHERE ARTIST_NAME = 'Nguyen Van A')),
    ('Xyz', '3min', 'Female', (SELECT ARTIST_ID FROM ARTIST WHERE ARTIST_NAME = 'Nguyen Thi B')),
    ('123', '1min', 'Male', (SELECT ARTIST_ID FROM ARTIST WHERE ARTIST_NAME = 'Tran C'));
    
INSERT INTO AUTHOR (AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME) VALUES
	('Abc', '123'),
    ('Herbert', 'Schildt');

INSERT INTO BOOK (BOOK_TITLE, BOOK_ISBN, BOOK_PAGE_COUNT, AUTHOR_ID) VALUES
	('C Sharp', '12345798', 728, (SELECT AUTHOR_ID FROM AUTHOR WHERE AUTHOR_FIRST_NAME = 'Abc')),
	('Golang', '98215', 548, (SELECT AUTHOR_ID FROM AUTHOR WHERE AUTHOR_FIRST_NAME = 'Abc')),
    ('Java: A Beginners Guide, Sixth Edition', '0071809252', 728, (SELECT AUTHOR_ID FROM AUTHOR WHERE AUTHOR_FIRST_NAME = 'Herbert'));